SEO Optimisation
autiinpu2/timer-sonneries pull request #38
Opened 2024-06-18 18:48 UTC by racloody

Optimisation of SEO by adding meta tags (description, author, viewport and robots).

2024-06-18 19:34 UTC, Adastram1 reviewed
Works for me

2024-06-18 21:30 UTC, yannis300307 requested changes

2024-06-18 21:30 UTC, yannis300307 commented on main.html
The quote character is not the same between the meta tag name and the description. I think it can cause syntax errors and it creates inconsistencies. Please replace the wrong character by `"`. Anyway, this is a good feature.

2024-06-18 22:40 UTC, racloody commented on main.html
> +    <meta name="description" content="Dring time est un site Internet qui vous indique dans combien de temps est ce que
Done !

2024-06-19 07:13 UTC, yannis300307 commented
Ok

2024-06-19 07:13 UTC, yannis300307 approved these changes

2024-06-19 07:14 UTC, merged