add brab animation for canvas moves
autiinpu2/timer-sonneries pull request #50
Opened 2024-09-06 09:03 UTC by autiinpu2

2024-09-06 16:02 UTC, yannis300307 requested changes

2024-09-06 16:02 UTC, yannis300307 commented on activities/canva-viewer.html
> +                grabDiv.style.cursor = "grab";
Il vaut mieux mettre le curseur à "" au lieu de "grab" car le curseur par défaut est déjà définit dans le CSS. En faisant cela, cela donne le contrôle du curseur au CSS et non au JS.

2024-09-06 16:06 UTC, autiinpu2 commented on activities/canva-viewer.html
> +                grabDiv.style.cursor = "grab";
jez m'occupe de ca demain alors

2024-09-11 15:01 UTC, yannis300307 approved these changes

2024-09-11 15:02 UTC, merged