News
autiinpu2/timer-sonneries pull request #72
Opened 2024-12-15 23:10 UTC by autiinpu2

2024-12-15 23:13 UTC, autiinpu2 commented
le seul problème est qu'il faut ajoute manuellement dans le Json les nouvelles features

2024-12-16 12:02 UTC, yannis300307 commented
Tu devrais utiliser l'API Github ou implémenter une section pour les admins dans les comptes. Le plus clean serait de récupérer la liste des commits.

2024-12-16 12:03 UTC, yannis300307 requested changes
Changer le json est vraiment horrible à faire

2024-12-16 15:14 UTC, yannis300307 commented
Et on met les commits en français stp.

2024-12-16 15:42 UTC, yannis300307 commented
[https://api.github.com/repos/PardaSuperDev/DringTime/commits](https://api.github.com/repos/PardaSuperDev/DringTime/commits)

2025-03-20 08:26 UTC, closed without merging

2025-03-20 11:09 UTC, yannis300307 commented
Tu veux delete la branche ?